-- dodatkowe
CREATE INDEX idx_Users_translatorID ON Users(translatorID);
CREATE INDEX idx_Users_webinarUserID ON Users(webinarUserID);
CREATE INDEX idx_Users_webinarTeacherID ON Users(webinarTeacherID);
CREATE INDEX idx_Users_courseUserID ON Users(courseUserID);
CREATE INDEX idx_Users_courseTeacherID ON Users(courseTeacherID);
CREATE INDEX idx_Users_studiesUserID ON Users(studiesUserID);
CREATE INDEX idx_Users_studiesTeacherID ON Users(studiesTeacherID);
CREATE INDEX idx_Users_studiesOutsiderID ON Users(studiesOutsiderID);

-- klucze glowne, inne co moga byc potrzebne
CREATE INDEX idx_AccessTimeLaws_accessTimeLawID ON AccessTimeLaws(accessTimeLawID);
CREATE INDEX idx_DaysOfPracticeLaws_daysOfPracticeLawID ON DaysOfPracticeLaws(daysOfPracticeLawID);
CREATE INDEX idx_MaxDaysForPayementBeforeCourseLaws_maxDaysForPayementBeforeCourseLawID ON MaxDaysForPayementBeforeCourseLaws(maxDaysForPayementBeforeCourseLawID);
CREATE INDEX idx_MaxDaysForPayementBeforeStudiesLaws_maxDaysForPayementBeforeStudiesLawID ON MaxDaysForPayementBeforeStudiesLaws(maxDaysForPayementBeforeStudiesLawID);
CREATE INDEX idx_MinAttendanceToPassCourseLaws_minAttendanceToPassCourseLawsID ON MinAttendanceToPassCourseLaws(minAttendanceToPassCourseLawsID);
CREATE INDEX idx_MinAttendanceToPassPracticeLaws_minAttendanceToPassPracticeLawID ON MinAttendanceToPassPracticeLaws(minAttendanceToPassPracticeLawID);
CREATE INDEX idx_MinAttendanceToPassStudiesLaws_minAttendanceToPassStudiesLawID ON MinAttendanceToPassStudiesLaws(minAttendanceToPassStudiesLawID);

CREATE INDEX idx_Webinars_webinarID ON Webinars(webinarID);
CREATE INDEX idx_Webinars_webinarTeacherID ON Webinars(webinarTeacherID);
CREATE INDEX idx_Webinars_translatorID ON Webinars(translatorID);



CREATE INDEX idx_WebinarToUserAssignment_webinarID ON WebinarsToUserAssignment(webinarID);
CREATE INDEX idx_WebinarToUserAssignment_webinarUserID ON WebinarsToUserAssignment(webinarUserID);

CREATE INDEX idx_WebinarUsers_webinarUserID ON WebinarUsers(webinarUserID);

CREATE INDEX idx_WebinarTeacher_webinarTeacherID ON WebinarTeacher(webinarTeacherID);

CREATE INDEX idx_WebinarDataChangeHistory_webinarID ON WebinarsDataChangeHistory(webinarID);
CREATE INDEX idx_WebinarDataChangeHistory_dateOfChange ON WebinarsDataChangeHistory(dateOfChange);

CREATE INDEX idx_WebinarUserDataChangeHistory_webinarUserID ON WebinarUsersDataChangeHistory(webinarUserID);
CREATE INDEX idx_WebinarUserDataChangeHistory_dateOfChange ON WebinarUsersDataChangeHistory(dateOfChange);

CREATE INDEX idx_WebinarTeacherDataChangeHistory_webinarTeacherID ON WebinarTeacherDataChangeHistory(webinarTeacherID);
CREATE INDEX idx_WebinarTeacherDataChangeHistory_dateOfChange ON WebinarTeacherDataChangeHistory(dateOfChange);

CREATE INDEX idx_Users_userID ON Users(userID);

CREATE INDEX idx_OrderHistory_orderID ON OrderHistory(orderID);
CREATE INDEX idx_OrderHistory_userID ON OrderHistory(userID);

CREATE INDEX idx_UsersDataChangeHistory_userID ON UsersDataChangeHistory(userID);
CREATE INDEX idx_UsersDataChangeHistory_dateOfChange ON UsersDataChangeHistory(dateOfChange);

CREATE INDEX idx_UserSessionHistory_sessionId ON UserSessionHistory(sessionId);
CREATE INDEX idx_UserSessionHistory_userID ON UserSessionHistory(userID);

CREATE INDEX idx_Translators_translatorID ON Translators(translatorID);

CREATE INDEX idx_TranslatorsDataChangeHistory_translatorID ON TranslatorsDataChangeHistory(translatorID);
CREATE INDEX idx_TranslatorsDataChangeHistory_dateOfChange ON TranslatorsDataChangeHistory(dateOfChange);

CREATE INDEX idx_StudiesUserAssignmentToStudiesSubject_studiesUserID ON StudiesUserAssignmentToStudiesSubject(studiesUserID);
CREATE INDEX idx_StudiesUserAssignmentToStudiesSubject_studiesSubjectID ON StudiesUserAssignmentToStudiesSubject(studiesSubjectID);

CREATE INDEX idx_AdminSessionHistory_sessionId ON AdminSessionHistory(sessionId);
CREATE INDEX idx_AdminSessionHistory_adminID ON AdminSessionHistory(adminID);

CREATE INDEX idx_Administrators_adminID ON Administrators(adminID);

CREATE INDEX idx_AdministratorsDataChangeHistory_adminID ON AdministratorsDataChangeHistory(adminID);
CREATE INDEX idx_AdministratorsDataChangeHistory_dateOfChange ON AdministratorsDataChangeHistory(dateOfChange);

CREATE INDEX idx_CourseModulePresence_courseUserID ON CourseModulePresence(courseUserID);
CREATE INDEX idx_CourseModulePresence_moduleID ON CourseModulePresence(moduleID);
CREATE INDEX idx_CourseModulePresence_courseID ON CourseModulePresence(courseID);

CREATE INDEX idx_CourseModules_courseID ON CourseModules(courseID);
CREATE INDEX idx_CourseModules_moduleID ON CourseModules(moduleID);

CREATE INDEX idx_CourseModulesDataChangeHistory_courseID ON CourseModulesDataChangeHistory(courseID);
CREATE INDEX idx_CourseModulesDataChangeHistory_moduleID ON CourseModulesDataChangeHistory(moduleID);
CREATE INDEX idx_CourseModulesDataChangeHistory_dateOfChange ON CourseModulesDataChangeHistory(dateOfChange);

CREATE INDEX idx_CourseTeacher_courseTeacherID ON CourseTeacher(courseTeacherID);

CREATE INDEX idx_CourseTeacherDataChangeHistory_courseTeacherID ON CourseTeacherDataChangeHistory(courseTeacherID);
CREATE INDEX idx_CourseTeacherDataChangeHistory_dateOfChange ON CourseTeacherDataChangeHistory(dateOfChange);

CREATE INDEX idx_CourseToUserAssignment_courseUserID ON CourseToUserAssignment(courseUserID);
CREATE INDEX idx_CourseToUserAssignment_courseID ON CourseToUserAssignment(courseID);

CREATE INDEX idx_CourseUsers_courseUserID ON CourseUsers(courseUserID);

CREATE INDEX idx_CourseUsersDataChangeHistory_courseUserID ON CourseUsersDataChangeHistory(courseUserID);
CREATE INDEX idx_CourseUsersDataChangeHistory_dateOfChange ON CourseUsersDataChangeHistory(dateOfChange);

CREATE INDEX idx_CourseWebinars_courseWebinarID ON CourseWebinars(courseWebinarID);

CREATE INDEX idx_CourseWebinarsDataChangeHistory_courseWebinarID ON CourseWebinarsDataChangeHistory(courseWebinarID);
CREATE INDEX idx_CourseWebinarsDataChangeHistory_dateOfChange ON CourseWebinarsDataChangeHistory(dateOfChange);

CREATE INDEX idx_Courses_courseID ON Courses(courseID);



CREATE INDEX idx_CoursesShoppingItem_courseID ON CoursesShoppingItem(courseID);
CREATE INDEX idx_CoursesShoppingItem_courseUserID ON CoursesShoppingItem(courseUserID);

CREATE INDEX idx_CoursesShoppingItemHistory_courseID ON CoursesShoppingItemHistory(courseID);
CREATE INDEX idx_CoursesShoppingItemHistory_courseUserID ON CoursesShoppingItemHistory(courseUserID);


CREATE INDEX idx_FieldOfStudies_fieldOfStudiesID ON FieldOfStudies(fieldOfStudiesID);



CREATE INDEX idx_Lessons_lessonID ON Lessons(lessonID);
CREATE INDEX idx_Lessons_studiesSubjectID ON Lessons(studiesSubjectID);

CREATE INDEX idx_LessonsDataChangeHistory_lessonID ON LessonsDataChangeHistory(lessonID);
CREATE INDEX idx_LessonsDataChangeHistory_studiesSubjectID ON LessonsDataChangeHistory(studiesSubjectID);
CREATE INDEX idx_LessonsDataChangeHistory_dateOfChange ON LessonsDataChangeHistory(dateOfChange);



CREATE INDEX idx_StudiesUserDataChangeHistory_studiesUserID ON StudiesUserDataChangeHistory(studiesUserID);
CREATE INDEX idx_StudiesUserDataChangeHistory_dateOfChange ON StudiesUserDataChangeHistory(dateOfChange);

CREATE INDEX idx_StudiesTeacherDataChangeHistory_studiesTeacherID ON StudiesTeacherDataChangeHistory(studiesTeacherID);
CREATE INDEX idx_StudiesTeacherDataChangeHistory_dateOfChange ON StudiesTeacherDataChangeHistory(dateOfChange);

CREATE INDEX idx_StudiesUser_studiesUserID ON StudiesUser(studiesUserID);

CREATE INDEX idx_StudiesTeacher_studiesTeacherID ON StudiesTeacher(studiesTeacherID);

CREATE INDEX idx_OutsidersDataChangeHistory_outsiderID ON OutsidersDataChangeHistory(outsiderID);
CREATE INDEX idx_OutsidersDataChangeHistory_dateOfChange ON OutsidersDataChangeHistory(dateOfChange);

CREATE INDEX idx_Outsiders_outsiderID ON Outsiders(outsiderID);

CREATE INDEX idx_StudiesUserAttendance_studiesUserID ON StudiesUserAttendance(studiesUserID);
CREATE INDEX idx_StudiesUserAttendance_lessonID ON StudiesUserAttendance(lessonID);

CREATE INDEX idx_WebinarsShoppingItem_webinarID ON WebinarsShoppingItem(webinarID);
CREATE INDEX idx_WebinarsShoppingItem_webinarUserID ON WebinarsShoppingItem(webinarUserID);

CREATE INDEX idx_WebinarsShoppingItemHistory_webinarID ON WebinarsShoppingItemHistory(webinarID);
CREATE INDEX idx_WebinarsShoppingItemHistory_webinarUserID ON WebinarsShoppingItemHistory(webinarUserID);
CREATE INDEX idx_WebinarsShoppingItemHistory_mainOrderID ON WebinarsShoppingItemHistory(mainOrderID);

CREATE INDEX idx_StudiesShoppingItemForStudiesUser_studiesUserID ON StudiesShoppingItemForStudiesUser(studiesUserID);
CREATE INDEX idx_StudiesShoppingItemForStudiesUser_fieldOfStudiesID ON StudiesShoppingItemForStudiesUser(fieldOfStudiesID);

CREATE INDEX idx_StudiesShoppingItemForStudiesUserHistory_studiesUserID ON StudiesShoppingItemForStudiesUserHistory(studiesUserID);
CREATE INDEX idx_StudiesShoppingItemForStudiesUserHistory_mainOrderID ON StudiesShoppingItemForStudiesUserHistory(mainOrderID);

CREATE INDEX idx_StudiesShoppingItemForOutsiders_studiesUserID ON StudiesShoppingItemForOutsiders(studiesUserID);
CREATE INDEX idx_StudiesShoppingItemForOutsiders_fieldOfStudiesID ON StudiesShoppingItemForOutsiders(fieldOfStudiesID);

CREATE INDEX idx_StudiesShoppingItemForOutsidersHistory_studiesUserID ON StudiesShoppingItemForOutsidersHistory(studiesUserID);
CREATE INDEX idx_StudiesShoppingItemForOutsidersHistory_mainOrderID ON StudiesShoppingItemForOutsidersHistory(mainOrderID);